### ISSUE TITLE
upgrading to latest braintree sdk

### ISSUE THREAD

**Issue by jamesdixon** [Justin-Credible/cordova-plugin-braintree#16]
@Justin-Credible first off, thanks for your hard work on this!

I noticed #3 and was curious if you had any idea on the level of effort involved to upgrade the plugin to the latest Braintree has to offer?

Admittedly, I'm unfamiliar with cordova plugins, but I'm more than willing to help. It'd be great if we could tag team the effort or if you don't have any time, it'd be great if you could point me in the right direction.

Thanks!
James

**Comment by Justin-Credible** [comment]
@jamesdixon We ended up using the JavaScript SDK in our Cordova app, which is why I haven't updated this plugin in a while.

I just resolved #3 with a new build hook, so upgrading the SDK version should be easier now.

IIRC, I used Carthage to build the Framework bundles and then copied them into this repo. As long as nothing major has changed in the SDK, this is all that should need to be done to upgrade. I'll see if I can get to that soon.

**Comment by Justin-Credible** [comment]
Alright, I've got a branch that upgrades the SDK to 4.7.3 for iOS and 2.3.12 for Android.

I've confirmed iOS working with the new SDK, but I haven't gotten to try Android yet. Once I confirm Android working I'll merge and release it as version 0.5.2.

In the mean time, you can add the plugin via:

```
cordova plugin add https://github.com/Justin-Credible/cordova-plugin-braintree#feature/upgrade-braintree-sdk
```

**Comment by jamesdixon** [comment]
Wow, that's awesome. Thanks a ton, @Justin-Credible! I'll give it a go this evening and report back.

Cheers!

**Comment by jamesdixon** [comment]
@Justin-Credible just ran a build and did get an error with Android. Here's the output:

```
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:12: error: cannot fi
nd symbol
import com.braintreepayments.api.BraintreePaymentActivity;
                                ^
  symbol:   class BraintreePaymentActivity
  location: package com.braintreepayments.api
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:13: error: cannot fi
nd symbol
import com.braintreepayments.api.PaymentRequest;
                                ^
  symbol:   class PaymentRequest
  location: package com.braintreepayments.api
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:30: error: cannot fi
nd symbol
    private PaymentRequest paymentRequest = null;
            ^
  symbol:   class PaymentRequest
  location: class BraintreePlugin
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:84: error: cannot fi
nd symbol
        paymentRequest = new PaymentRequest().clientToken(token);
                             ^
  symbol:   class PaymentRequest
  location: class BraintreePlugin
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:172: error: cannot f
ind symbol
                paymentMethodNonce = intent.getParcelableExtra(BraintreePaymentActivity.EXTRA_PAYMENT_METHOD_N
ONCE);
                                                               ^
  symbol:   variable BraintreePaymentActivity
  location: class BraintreePlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 58.757 secs
Error: /Users/greenhouse/tmp_aQRih/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:12: error: cannot fi
nd symbol
import com.braintreepayments.api.BraintreePaymentActivity;
                                ^
  symbol:   class BraintreePaymentActivity
  location: package com.braintreepayments.api
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:13: error: cannot fi
nd symbol
import com.braintreepayments.api.PaymentRequest;
                                ^
  symbol:   class PaymentRequest
  location: package com.braintreepayments.api
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:30: error: cannot fi
nd symbol
    private PaymentRequest paymentRequest = null;
            ^
  symbol:   class PaymentRequest
  location: class BraintreePlugin
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:84: error: cannot fi
nd symbol
        paymentRequest = new PaymentRequest().clientToken(token);
                             ^
  symbol:   class PaymentRequest
  location: class BraintreePlugin
/Users/greenhouse/tmp_aQRih/platforms/android/src/net/justincredible/BraintreePlugin.java:172: error: cannot f
ind symbol
                paymentMethodNonce = intent.getParcelableExtra(BraintreePaymentActivity.EXTRA_PAYMENT_METHOD_N
ONCE);
                                                               ^
  symbol:   variable BraintreePaymentActivity
  location: class BraintreePlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


Build failed :|
Failed to compile
```

**Comment by Taracque** [comment]
That's because in Drop-in 3.0 PaymentRequest has been renamed to DropInRequest.
I'm working on it, once I'm ready I'll post it here…

**Comment by Taracque** [comment]
Check this for android:
https://github.com/Taracque/cordova-plugin-braintree/commit/a8cae13efc38c7f753a30993a0f85559b5c743d7
I've tested, and card payment works in sandbox mode (so it should be ok), but clicking on PayPal doesn't.

**Comment by Taracque** [comment]
Ok, for me works fully on Android if https://github.com/Taracque/cordova-plugin-braintree/commit/8f621d98c7cf5c2c0a1fa868f6a5b8ad0db5cebc also applied. (PayPal needs the AndroidManifest keys)

**Comment by jamesdixon** [comment]
@Taracque I tried that commit, but getting the original error from #15 

Interestingly, I didn't see the error from #15 in this branch, just the above issue

**Comment by Taracque** [comment]
You can make a try with my latest, i386 code was not included in all frameworks

**Comment by jamesdixon** [comment]
@Taracque your latest resolved by issue, but the build is failing when building iOS for a different reason. 

The actual failure message is:

```

The following build commands failed:
CompileC /Users/greenhouse/Library/Developer/Xcode/DerivedData/Scout_Customer-gkexotprqfvvkpffmnagbawfgilp/Bui
ld/Intermediates/ArchiveIntermediates/Scout\ Customer/IntermediateBuildFilesPath/Scout\ Customer.build/Debug-i
phoneos/Scout\ Customer.build/Objects-normal/armv7/BraintreePlugin.o Scout\ Customer/Plugins/cordova-plugin-br
aintree/BraintreePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/greenhouse/tmpLs13i2/platforms/ios/co
rdova/build-debug.xcconfig,-workspace,Scout Customer.xcworkspace,-scheme,Scout Customer,-configuration,Debug,-
destination,generic/platform=iOS,-archivePath,Scout Customer.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/
greenhouse/tmpLs13i2/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/greenhouse/tmpLs13i2/platforms/ios/
build/sharedpch
```

Another interesting thing I noticed was the following message:

```
Script file does't exist and will be skipped: /Users/greenhouse/tmpLs13i2/plugins/cordova-plugin-braintree/hoo
ks/add_embedded_ios_frameworks.js.js
```

Here's the full log: https://gist.github.com/jamesdixon/ab1557c08fe2e22c81c9e257a7c012af

Thanks for your help with this!

**Comment by Taracque** [comment]
It seems that PassKit is not included in your xcode project. Try to open the Xcode project, add PassKit and try to compile…

**Comment by jamesdixon** [comment]
Thanks @Taracque. Is PassKit something that's required by Braintree? I'm using a CI service called Greenhouse to do my builds, so curious how I could add PassKit to make it work.

**Comment by Taracque** [comment]
Ok, the problem is that your build system is using ios sdk 9. However BraintreeApplePay module is usign the PKPaymentNetwork https://developer.apple.com/reference/passkit/pkpaymentnetwork structure, which is new in the IOS 10 SDK.
Can you try to switch your base sdk to ios 10?

**Comment by jamesdixon** [comment]
@Taracque that was the issue. Thank you very much for your assistance and hard work. It's much appreciated!

**Comment by jamesdixon** [comment]
@Taracque sorry to be a pest, but another question for you:

I ran my app and it crashes immediately. It turns out the Paypal Framework doesn't seem to be found. Is there something that needs to be done to make this happen?

Crash Log:

```
Incident Identifier: 439FD790-B42D-4509-941F-8D547E7D041D
CrashReporter Key:   52a55a77c8c09c4fee0c5806d6bfee8d9dc5e774
Hardware Model:      iPhone7,2
Process:             Scout Customer [216]
Path:                /private/var/containers/Bundle/Application/78E732EB-27EB-4297-B814-6D6FA2A2079E/Scout Customer.app/Scout Customer
Identifier:          com.scoutforpets.customer
Version:             62 (0.0.1)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2016-12-02 11:16:12.12 -0700
Launch Time:         2016-12-02 11:16:12.12 -0700
OS Version:          iOS 9.3.5 (13G36)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001200bd088
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils
  Referenced from: /var/containers/Bundle/Application/78E732EB-27EB-4297-B814-6D6FA2A2079E/Scout Customer.app/Scout Customer
  Reason: image not found
  Dyld Version: 390.7

Binary Images:
0x10003c000 - 0x1001b3fff Scout Customer arm64  <3d2652873d68353b93c21d38d6be6c53> /var/containers/Bundle/Application/78E732EB-27EB-4297-B814-6D6FA2A2079E/Scout Customer.app/Scout Customer
0x1200bc000 - 0x1200ebfff dyld arm64  <a1862e29910f3f069a363730df77dad7> /usr/lib/dyld
```

**Comment by Taracque** [comment]
That's because PayPalUtils.framework is not embeded in Xcode. I've no idea how you can check this without a real xcode. Normally in Build Phases there should be an Embed Frameworks step where all Braintree/PayPal frameworks must be listed (with Code Sign On Copy turned on)

**Comment by jamesdixon** [comment]
Does this have anything to do with the hook error that I mentioned earlier?

```
Script file does't exist and will be skipped: /Users/greenhouse/tmpLs13i2/plugins/cordova-plugin-braintree/hoo
ks/add_embedded_ios_frameworks.js.js
```

It looks like there is an extra `.js` tacked on to the end of the file name.

**Comment by Taracque** [comment]
Yes, that is the problem. I’ve fixed that in my github repo. Give it a try.

**Comment by jamesdixon** [comment]
Hmm. Unfortunately, still the same issue.

It seems that even though the hook runs, the embedded frameworks are never added.

**Comment by jamesdixon** [comment]
Are you manually adding yours?

**Comment by jamesdixon** [comment]
@Justin-Credible any thoughts on this?

**Comment by Taracque** [comment]
I've changed the hook in my copy. Now it works for me (however I've to change the type to after_build)

**Comment by jamesdixon** [comment]
Tried with the updated version and it failed quickly with yet a new error:

```
no dir  platforms/ios
Error: ENOENT: no such file or directory, open '/Users/greenhouse/tmp0abLuB/undefined/project.pbxproj'
```

**Comment by Taracque** [comment]
The directory platforms/ios exists in you project directory (/Users/greenhouse/tmp0abLuB/platforms/ios/) ?

**Comment by jamesdixon** [comment]
I don't commit the directory into source control. It's built by the CI. For what it's worth, it builds fine with the previous version of the build file -- the embedded frameworks just don't appear to be added properly.

**Comment by Taracque** [comment]
Sorry, I've no idea. For me `ionic plugin add …` and `ionic build ios` put the frameworks with the right settings to the xcode project.

**Comment by jamesdixon** [comment]
No problem. I appreciate all of your help. It does build for Android, so it would seem that the directory location is correct.

**Comment by Taracque** [comment]
Maybe changeing the hook from after_build to before_build. Can you try it?

**Comment by jamesdixon** [comment]
@Taracque my debugging situation is less than optimal as I'm on an older version of OS X and can't seem to get the latest XCode version installed to debug locally. That said, I'm debugging purely through the logs of my CI service. 

I was able to figure out a few things though:

This block of code doesn't seem to work. The hook would run even if the platform was Android. 
```
if(process.length >=5 && process.argv[1].indexOf('cordova') == -1) {
        if(process.argv[4] != 'ios') {
            return; // plugin only meant to work for ios platform.
        }
    }
```

That said, I reverted back to your previous method of checking the context for the platform of the plugin, and it works as expected. This is why I was receiving the error that no dir existed -- iOS hadn't been added yet.

The other issue I ran into was [this line](https://github.com/Taracque/cordova-plugin-braintree/blob/master/hooks/add_embedded_ios_frameworks.js#L90) was returning the name of my project encapsulated in quotes, which was causing the plugin path to be incorrect. For example, my project is called `Scout` and it was returned as `"Scout"`, which resulted in `pluginPathInPlatformIosDir` to be `"Scout"/Plugins/cordova-plugin-braintree`.

After fixing those two issues, I was able to get the project building again. However, it still fails with:

```
Incident Identifier: 63ECB514-83EB-469A-9E75-DC5C1B93FDD1
CrashReporter Key:   52a55a77c8c09c4fee0c5806d6bfee8d9dc5e774
Hardware Model:      iPhone7,2
Process:             Scout Customer [425]
Path:                /private/var/containers/Bundle/Application/634469A8-7D30-43B9-9F32-3C533DE06B2F/Scout Customer.app/Scout Customer
Identifier:          com.scoutforpets.customer
Version:             69 (0.0.1)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2016-12-02 18:27:28.28 -0700
Launch Time:         2016-12-02 18:27:28.28 -0700
OS Version:          iOS 9.3.5 (13G36)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001200d5088
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils
  Referenced from: /var/containers/Bundle/Application/634469A8-7D30-43B9-9F32-3C533DE06B2F/Scout Customer.app/Scout Customer
  Reason: image not found
  Dyld Version: 390.7

Binary Images:
0x1000a0000 - 0x100217fff Scout Customer arm64  <a1419081d50735a49d670c57a4395fb8> /var/containers/Bundle/Application/634469A8-7D30-43B9-9F32-3C533DE06B2F/Scout Customer.app/Scout Customer
0x1200d4000 - 0x120103fff dyld arm64  <a1862e29910f3f069a363730df77dad7> /usr/lib/dyld
```

**Comment by Taracque** [comment]
I've checked an my PayPalUtils contains the arm64 code:

```bash
file .../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils
.../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils: Mach-O universal binary with 4 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [arm_v7: Mach-O dynamically linked shared library arm_v7] [arm64: Mach-O 64-bit dynamically linked shared library arm64]
.../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils (for architecture i386):	Mach-O dynamically linked shared library i386
.../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
.../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
.../cordova-plugin-braintree/lib/ios/PayPalUtils.framework/PayPalUtils (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Maybe something removes it. Can you make a `file  PayPalUtils.framework/PayPalUtils`?

**Comment by jamesdixon** [comment]
I've abandoned trying to get this to work on my CI server. I finally upgraded to OS X Sierra and it's building the project properly. However, when I open up XCode, I'm seeing the following error:

![image](https://cloud.githubusercontent.com/assets/110114/20863340/cdd75a98-b984-11e6-9a33-c28650e47e79.png)

Have you run into this one before?

So frustrating!

**Comment by jamesdixon** [comment]
@Taracque it seems that the framework files are embedded, but can't be found at runtime. This occurs for any of the Braintree headers that are linked by the plugin. Any suggestions?

**Comment by Taracque** [comment]
Can you check that the frameworks has been included in Link Binary With Libraries build phase with Required status, and also check your Runpath Search Paths settings in xcode (that should contain "@executable_path/Frameworks"

**Comment by hussainak** [comment]
@Taracque 
Adding frameworks in General>Embedded Binaries seems to get rid of the Library not loaded: @rpath/PayPalUtils.framework/PayPalUtils issue.
![image](https://cloud.githubusercontent.com/assets/1008911/20886525/82c21f4e-bb4a-11e6-9ca9-8498d297ee13.png)

However, PayPal still throws the following message from BrainTree SDK
[BraintreeSDK] CRITICAL PayPal requires [BTAppSwitch setReturnURLScheme:] to be configured to begin with your app's bundle ID (au.org.abcd). Currently, it is set to (au.org.abcd.payments).

**Comment by jamesdixon** [comment]
@Taracque everything seems to be where it needs to be:

![image](https://cloud.githubusercontent.com/assets/110114/20900945/80b0b966-baed-11e6-8a6b-65eb4041ed64.png)

![image](https://cloud.githubusercontent.com/assets/110114/20900958/8e10abca-baed-11e6-9b40-ace2804ae2a4.png)

@hussainak have you received any sort of message about imports not being found as I mentioned above?

**Comment by jamesdixon** [comment]
I was actually able to build without issue if I build against a generic iOS device. However, building to run on an emulator fails. Something missing to make this work?

**Comment by Taracque** [comment]
The emulator itself is an i386/x86_64 device, so it uses a diferrent binary. Do you have any error codes where the compilation fails?
@hussainak please check you URLs handlers in your xcode project. I've put a directive into my version of the BT plugin which puts the directive into the Info.plist. If you have added it manually the 2 directives can conflict with each other.

**Comment by jamesdixon** [comment]
@Taracque the only error is 

```
/platforms/ios/Scout/Plugins/cordova-plugin-braintree/BraintreePlugin.m:9:9: 'BraintreeUI/BTPaymentRequest.h' file not found
```

However, if I remove the reference to this file, the next Braintree header fails. It seems that it cannot find any of them when attempting to install on the emulator.

**Comment by jamesdixon** [comment]
Also, this appears to occur regardless of which version of iOS the emulator is running.

**Comment by jamesdixon** [comment]
Just tried installing to my phone through XCode and also seeing the same error.

**Comment by Taracque** [comment]
Can you try a new empty project with only the BT plugin installed to see what happens there?

**Comment by hussainak** [comment]
@jamesdixon yea I had that error before, all i did was removed the plugin with all its stale files and re installed the plugin again. Doing this rid me of that error.

**Comment by jamesdixon** [comment]
@Taracque I'll give it a shot.

@hussainak thanks. were you able to resolve the other issue you were having?

**Comment by hussainak** [comment]
@jamesdixon 
Sorry couldnt reply earlier. Yes, I replaced ${PRODUCT_BUNDLE_IDENTIFIER}.payments with actual bundle ID in my plist and PayPal worked

**Comment by Sionarch** [comment]
Thanks for your great work. I want to confirm that the BT frameworks has to be added manually to Embedded Binaries for the build to succeed (Xcode 8.1). I don't know how to solve this but hope I will be able to contribute in other ways!

**Comment by Sionarch** [comment]
The context.opts.plugin property doesn't exist for me (Cordova 6.4.0) and thus the hook fails to detect that I'm building for iOS. I'm instead using the method from Justin's https://github.com/Justin-Credible/cordova-plugin-braintree/pull/17/commits/c1a1fff5b18ab772dcf38c2c0bef982e540f8c89.

**Comment by Taracque** [comment]
For me the `(process.length >=5 && process.argv[1].indexOf('cordova') == -1)` is false, and case of that the hooks is runs on android as well.
It seems that the embed framework step needs to be rewriten as it is not works in all cases.

**Comment by jamesdixon** [comment]
> The context.opts.plugin property doesn't exist for me (Cordova 6.4.0) and thus the hook fails to detect that I'm building for iOS.

> For me the (process.length >=5 && process.argv[1].indexOf('cordova') == -1) is false, and case of that the hooks is runs on android as well.

I can confirm that I'm seeing different behavior with these calls. I'm not sure if it's a Node/Cordova-version issue, but I've seen both work and both fail. That said, I'm thinking it probably wouldn't hurt to use both guards. Thoughts?

> It seems that the embed framework step needs to be rewriten as it is not works in all cases.

Agreed. That said, it appears they are being embedded -- they are showing up in XCode. Could it be the path that's being searched?

**Comment by jamesdixon** [comment]
@Sionarch would you mind explaining your process for adding the binaries manually? I still can't seem to get the project to build.

**Comment by Taracque** [comment]
I've just rewrite the hook in this version: https://github.com/Taracque/cordova-plugin-braintree/tree/io-dropin-5.0 (this one has ApplePay support and updated drop-in interface)
Run `npm install xcode` and `npm install plist` before install…

**Comment by jamesdixon** [comment]
@Taracque nice work. Unfortunately, I'm still having issues with the frameworks not being found even though they are showing as embedded.

**Comment by Taracque** [comment]
@jamesdixon for me it seems that your project is damaged. Make a backup, try to remove, ios platform, and add it again (`cordova platform rm ios --save` `cordova platform add ios --save`)

**Comment by hussainak** [comment]
@Taracque  Submitting to TestFlight or AppStore gives out the following errors because Embedded Binaries are not being Code Signed. Seen this before?

![image](https://cloud.githubusercontent.com/assets/1008911/20994962/ec724834-bd47-11e6-8330-7771dedbf184.png)

Also, gives the following:

ERROR ITMS-90087, ERROR ITMS-90209,  ERROR ITMS-90125, WARNING ITMS-90080

**Comment by Taracque** [comment]
Check the Embed Frameworks step in Build Phases. Code Sign on Copy must be checked for all PayPal/Braintree frameworks.

**Comment by hussainak** [comment]
@Taracque yea I have that checked but still same issue

**Comment by Taracque** [comment]
Ok, that dialog is not an error. Just inform you about the provisioning profile used.
ERROR ITMS-90087: Unsupported Architecture. ERROR ITMS - 90209 Invalid Segment Alignment, ERROR ITMS-90125: The Binary is invalid. WARNING ITMS-90080: PIE executable.

Can you copy the exact error message here?

Maybe your build contains i386, x86_64 code. Is you Archive build scheme uses Release build config? 

Also there should be a Run Script Build Phase (last one) which removes unused architecture codes. If not, check this page: http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by hussainak** [comment]
Tried that run script and it seems successfully clear unsupported architectures, thanks heaps @Taracque

**Comment by matejamateusz** [comment]
Hey everyone, I want to ask @Justin-Credible when you will plan to merge the update to master? Thanks ;)

**Comment by jamesdixon** [comment]
@Taracque getting back to this now. Which of your branches would be best to start with? I see some updates to both.

**Comment by Taracque** [comment]
io-dropin-5.0 should be good

**Comment by jamesdixon** [comment]
Has anyone been able to get this process to work _without_ having to re-add the binaries directly to the XCode project? We use a CI Server (Greenhouse CI) to do all of our builds, so this extra step to re-add the embedded binaries is not conducive to our workflow.

Thanks!

**Comment by jamesdixon** [comment]
@Taracque seeing this when using your io-dropin branch:

```
2017-01-06 00:06:16.044 Scout[35100:915489] PayPal OneTouchCoreSDK: callback URL scheme com.scoutforpets.customer.payments is not found in .plist
2017-01-06 00:06:16.044 Scout[35100:915489] [BraintreeSDK] CRITICAL PayPal requires [BTAppSwitch setReturnURLScheme:] to be configured to begin with your app's bundle ID (com.scoutforpets.customer). Currently, it is set to (com.scoutforpets.customer.payments).
```

I tried adding the following to plugin.xml, with no luck:

```
<config-file target="*-Info.plist" parent="CFBundleURLTypes">
      <array>
        <dict>
          <key>CFBundleURLSchemes</key>
          <array>
            <string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
          </array>
        </dict>
      </array>
    </config-file>
```

Any suggestions?

Thank you!

**Comment by Taracque** [comment]
In my fork the add_embedded_ios_frameworks.js hook adds the ${PRODUCT_BUNDLE_IDENTIFIER} string.
Your xml is wrong as it should be
`<string>${PRODUCT_BUNDLE_IDENTIFIER}.payments</string>
instead of
`<string>${PRODUCT_BUNDLE_IDENTIFIER}</string>

I suggest to post issues regarding to may for on my github, as it most of those have no sense with justins code.

**Comment by jamesdixon** [comment]
Thank you. Could you enable issues on your repo?
